/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3hBaWB7Uhe0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function PlayerStats() {
  return (
    <div className="flex flex-col items-center gap-6 px-4 py-8 md:px-6 lg:px-8">
      <div className="flex flex-col items-center gap-4">
        <img
          alt="Player Image"
          className="rounded-full"
          height={120}
          src="/placeholder.svg"
          style={{
            aspectRatio: "120/120",
            objectFit: "cover",
          }}
          width={120}
        />
        <h1 className="text-2xl font-bold">Virat Kohli</h1>
      </div>
      <div className="grid w-full max-w-4xl gap-6">
        <div className="grid gap-4">
          <h2 className="text-lg font-semibold">Batting Stats</h2>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Season</TableHead>
                <TableHead>Matches</TableHead>
                <TableHead>Runs</TableHead>
                <TableHead>Avg</TableHead>
                <TableHead>SR</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>Overall</TableCell>
                <TableCell>500</TableCell>
                <TableCell>12345</TableCell>
                <TableCell>55.55</TableCell>
                <TableCell>95.67</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2022</TableCell>
                <TableCell>20</TableCell>
                <TableCell>1234</TableCell>
                <TableCell>61.20</TableCell>
                <TableCell>92.31</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2021</TableCell>
                <TableCell>18</TableCell>
                <TableCell>1123</TableCell>
                <TableCell>62.39</TableCell>
                <TableCell>90.12</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2020</TableCell>
                <TableCell>15</TableCell>
                <TableCell>987</TableCell>
                <TableCell>65.80</TableCell>
                <TableCell>88.76</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2019</TableCell>
                <TableCell>22</TableCell>
                <TableCell>1456</TableCell>
                <TableCell>66.18</TableCell>
                <TableCell>94.23</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2018</TableCell>
                <TableCell>25</TableCell>
                <TableCell>1545</TableCell>
                <TableCell>61.80</TableCell>
                <TableCell>97.45</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
        <div className="grid gap-4">
          <h2 className="text-lg font-semibold">Bowling Stats</h2>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Season</TableHead>
                <TableHead>Matches</TableHead>
                <TableHead>Overs</TableHead>
                <TableHead>Wickets</TableHead>
                <TableHead>Avg</TableHead>
                <TableHead>Econ</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>Overall</TableCell>
                <TableCell>50</TableCell>
                <TableCell>200</TableCell>
                <TableCell>25</TableCell>
                <TableCell>30.50</TableCell>
                <TableCell>5.00</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2022</TableCell>
                <TableCell>10</TableCell>
                <TableCell>40</TableCell>
                <TableCell>5</TableCell>
                <TableCell>32.00</TableCell>
                <TableCell>5.50</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2021</TableCell>
                <TableCell>8</TableCell>
                <TableCell>35</TableCell>
                <TableCell>4</TableCell>
                <TableCell>35.75</TableCell>
                <TableCell>5.14</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2020</TableCell>
                <TableCell>7</TableCell>
                <TableCell>30</TableCell>
                <TableCell>3</TableCell>
                <TableCell>40.00</TableCell>
                <TableCell>6.00</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2019</TableCell>
                <TableCell>12</TableCell>
                <TableCell>50</TableCell>
                <TableCell>7</TableCell>
                <TableCell>28.57</TableCell>
                <TableCell>4.80</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>2018</TableCell>
                <TableCell>13</TableCell>
                <TableCell>45</TableCell>
                <TableCell>6</TableCell>
                <TableCell>27.33</TableCell>
                <TableCell>4.67</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
        <div className="grid gap-4">
          <h2 className="text-lg font-semibold">Batting Stats Against Teams</h2>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Team</TableHead>
                <TableHead>Matches</TableHead>
                <TableHead>Runs</TableHead>
                <TableHead>Avg</TableHead>
                <TableHead>SR</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>Australia</TableCell>
                <TableCell>30</TableCell>
                <TableCell>1234</TableCell>
                <TableCell>55.18</TableCell>
                <TableCell>92.67</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>England</TableCell>
                <TableCell>25</TableCell>
                <TableCell>987</TableCell>
                <TableCell>49.35</TableCell>
                <TableCell>90.12</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>South Africa</TableCell>
                <TableCell>20</TableCell>
                <TableCell>876</TableCell>
                <TableCell>58.40</TableCell>
                <TableCell>94.23</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>New Zealand</TableCell>
                <TableCell>18</TableCell>
                <TableCell>765</TableCell>
                <TableCell>51.00</TableCell>
                <TableCell>97.45</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Pakistan</TableCell>
                <TableCell>15</TableCell>
                <TableCell>654</TableCell>
                <TableCell>54.50</TableCell>
                <TableCell>95.67</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
        <div className="grid gap-4">
          <h2 className="text-lg font-semibold">Bowling Stats Against Teams</h2>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Team</TableHead>
                <TableHead>Matches</TableHead>
                <TableHead>Overs</TableHead>
                <TableHead>Wickets</TableHead>
                <TableHead>Avg</TableHead>
                <TableHead>Econ</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>Australia</TableCell>
                <TableCell>10</TableCell>
                <TableCell>40</TableCell>
                <TableCell>5</TableCell>
                <TableCell>32.00</TableCell>
                <TableCell>5.50</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>England</TableCell>
                <TableCell>8</TableCell>
                <TableCell>35</TableCell>
                <TableCell>4</TableCell>
                <TableCell>35.75</TableCell>
                <TableCell>5.14</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>South Africa</TableCell>
                <TableCell>7</TableCell>
                <TableCell>30</TableCell>
                <TableCell>3</TableCell>
                <TableCell>40.00</TableCell>
                <TableCell>6.00</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>New Zealand</TableCell>
                <TableCell>12</TableCell>
                <TableCell>50</TableCell>
                <TableCell>7</TableCell>
                <TableCell>28.57</TableCell>
                <TableCell>4.80</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Pakistan</TableCell>
                <TableCell>13</TableCell>
                <TableCell>45</TableCell>
                <TableCell>6</TableCell>
                <TableCell>27.33</TableCell>
                <TableCell>4.67</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  )
}
